### ISSUE TITLE
Selenium version upgrade

### ISSUE THREAD

**Issue by mkrzyzanowski** [Cognifide/bobcat#224]
# Todo

- [x] update Selenium version to the latest available
- [x] update BB codebase to compile and work with the latest Selenium
- [x] test as extensively as possible that the update did not break anything

**Comment by mkrzyzanowski** [comment]
Released in 1.3.0
