### ISSUE TITLE
AEM 6.5 Authoring 

### ISSUE THREAD

**Issue by Shaihuludus** [Cognifide/bobcat#322]
AEM 6.5 has been released and we need to be sure that Bobcat AEM authoring is ready for it.
Verify https://github.com/Cognifide/bobcat-aem-tests results to check the scope of potential changes.

## TODO
- [x] Create new module in bobcat for AEM 6.5 that will inherit from only from aem core (new package should also be introduced)
- [x] Create new Guice Modules (based on 6.4)
- [x] Validate which implementations has to be changed
- [x] Prepare new implementations and bind them in Guice in 6.5
- [x] Prepare tests https://github.com/Cognifide/bobcat-aem-tests for 6.5

**Comment by DeChrish** [comment]
@mkrzyzanowski can you release 6.5 support?

**Comment by mkrzyzanowski** [comment]
Released in `2.1.0`
